name = "cf-worker-ws-dev"
main = "src/index.js"
compatibility_date = "2026-06-16"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008,ProxyIP.HK.CMLiussss.net:443"
# UUID = "your-uuid-here"
# TROJAN_PASSWORD = "your-trojan-password"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
